### ISSUE TITLE
Passing Mol object

### ISSUE THREAD

**Issue by davide-grheco** [swansonk14/admet_ai#11]
Hello, thank you for the nice programmatic interface to the models.
Would it be possible to add a couple functions to the Model class to allow it to make predictions by passing it the Mol object directly or FP and descriptors?
I ask because in larger projects it is quite common to have the Mol object stores somewhere anyway and in this way I would not have to keep creating such object over and over.

Since I'll have to write a wrapper around the library I'll probably do it anyway, but it would be nice to have the functionality directly in the library.

**Comment by swansonk14** [comment]
Hi @davide-grheco,

Thank you for the suggestion! That's a great idea!

Just to clarify the interface, is the idea to modify the `ADMETModel`'s `predict` method to optionally take `Mol` objects and pre-computed RDKit fingerprints? Would you also have access to the SMILES so that you could pass them to `predict` as well, or would the `predict` method need to map `Mol` objects back to SMILES for the index of the output Pandas DataFrame?

If you have a specific design in mind and want to submit a PR, it would be highly appreciated! Otherwise, I can try to work on this in the near future.

Best,
Kyle

**Comment by davide-grheco** [comment]
Hello Kyle,
thank you for getting back to me. The idea would be either to modify the ADMETModel's predict method to optionally take a Mol object or to create a new method that executes using only the Mol object.
I didn't fully read the code in detail yet, so I do not have a clear idea of which architecture I'd prefer. Since the original method gives back a dictionary containing SMILES I would not change that to be consistent.
Here I can see a couple options:
1. Just pas the Mol object and generate the SMILES; this has the clear disadvantage that if you are using the SMILES to map the results to other data, if the generated SMILES does not match the original you'd have to do more work to validate that. As such this does not feel like a good solution.
2. Pass a list of Mol objects and associated identifiers. The identifiers could be SMILES or something else and would be used to map the results to other data after completing the calculation. I'd still compute the SMILES from the Mol object to not generate problems in the middle.
3. Pass a list of Mol objects and a list of SMILES, this functionality could probably just be added to the original function. The one problem here would be that you still would have to validate that the SMILES passed do match the Mol object and decide what to do if they do not.

Among these options I feel option 2 is the one that could be more widely useful and more robust. In any way we incur in the additional computing of the SMILES, but we remove the initialization of the Mol object. If any 3D embedding is happening somewhere, we could also remove that step by passing a 3D structure.
I do have some time available today, I'll take a look and get back to you. Unfortunately I'm off to a week of vacation in a couple days, so it could be that I cannot send you a fully working PR that quickly.

Davide

**Comment by swansonk14** [comment]
Hi Davide,

Thank you so much for your insightful thoughts on this issue! Yes I think you're right, it would be pretty challenging to avoid to recomputation of the Mol object from the SMILES given that ADMET-AI is currently pinned to Chemprop version 1.6.1. I hope that we will be able to shift to Chemprop v2 at some point, but unfortunately I likely won't have the bandwidth to work on that in the near future.

I'll close this issue for now, but please let me know if you run into any other issues or if you're interested in proposing changes to support Chemprop v2!

Best,
Kyle
