### ISSUE TITLE
Request for Help with ADMET Prediction Output

### ISSUE THREAD

**Issue by anhtuannbk** [swansonk14/admet_ai#13]
I recently came across your GitHub repository and have been using your code for ADMET predictions. I appreciate your work and the effort you put into this project.

I would like to know if you could assist me in modifying the code to export the ADMET prediction results along with the corresponding SMILES strings. This would be extremely helpful for my analysis.

Thank you for your time and assistance. I look forward to your response.

**Comment by swansonk14** [comment]
Hi @anhtuannbk,

I would be happy to help out! Can you share a bit more detail about what exactly you're looking for? ADMET-AI currently does save the SMILES and prediction results to a CSV file. Are you looking for a different export format or different data to be exported?

Thanks,
Kyle

**Comment by anhtuannbk** [comment]
Hi @swansonk14, 
Thank you so much for your response and willingness to help. I just wanted to let you know that I have managed to resolve the issue on my own.

I truly appreciate your time and support!

Thanks,
Tuan

**Comment by swansonk14** [comment]
Hi Tuan,

Great, I'm glad you were able to resolve the issue!

Best,
Kyle
