### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/xuhu/project/admet_ai/admet_ai/resources/data/reference_no_kd_ic50.csv'

### ISSUE THREAD

**Issue by xuhu0115** [swansonk14/admet_ai#2]
Hello,when I run the inference.py, I get this problem. Can you help me solve  the problem?

FileNotFoundError: [Errno 2] No such file or directory: '/home/xuhu/project/admet_ai/admet_ai/resources/data/reference_no_kd_ic50.csv'

**Comment by sherryliu987** [comment]
If you're struggling to run ADMET locally, feel free to try https://www.tamarind.bio/admet. Tamarind is an online platform for bioinformatics tools that offers computational biology workflows, including ADMET, for free.

**Comment by swansonk14** [comment]
Hi @xuhu0115,

Thank you for raising the issue! I don't recognize the `reference_no_kd_ic50.csv` file name. What exactly do you have in your `inference.py` file? Is `reference_no_kd_ic50.csv` one of your files?

Thanks,
Kyle

**Comment by swansonk14** [comment]
Hi @xuhu0115,

If you're still having a problem, please feel free to reopen this issue.

Thanks,
Kyle
