### ISSUE TITLE
How can I change the port for the web server?

### ISSUE THREAD

**Issue by Evert-Homan** [swansonk14/admet_ai#4]
Hi Kyle,

Thanks for making this great tool available to the public. By default the web server uses port 5000, but is there a way to change this, as many web tools by default use this port. Where is this configured?

Much appreciated/Evert

**Comment by Evert-Homan** [comment]
Thanks, I see the lines in the ./web/run.py file. Setting the port from the command line does not work on my machine:

`admet_web --port 5001
Failed to find the pandas get_adjustment() function to patch
Failed to patch pandas - PandasTools will have limited functionality
usage: admet_web [-h] [--secret_key SECRET_KEY]
                 [--session_lifetime SESSION_LIFETIME]
                 [--heartbeat_frequency HEARTBEAT_FREQUENCY]
                 [--max_molecules MAX_MOLECULES]
                 [--max_visible_molecules MAX_VISIBLE_MOLECULES]
                 [--no_cache_molecules]
admet_web: error: unrecognized arguments: --port 5001`

**Comment by Evert-Homan** [comment]
It works fine when I change the port in the run.py file, can even hardcode the host with the domain name. Great!

Best wishes/Evert

**Comment by swansonk14** [comment]
Hi Evert,

Sorry, my bad! I forgot that the command line arguments come from the `setup_web` function and not from the `admet_web` function in that file. Hardcoding the port and host in `run.py` should work.

Best,
Kyle
