### ISSUE TITLE
Local web server lacks molecule sketcher

### ISSUE THREAD

**Issue by Evert-Homan** [swansonk14/admet_ai#5]
Hi,

Now that I have a local install with web server up and running I note that there is no molecule sketcher app shown. Presumably something is lacking on my machine. Any ideas?

![admet_ai_mol_draw](https://github.com/swansonk14/admet_ai/assets/98899388/e0cdc0dc-e205-4a2e-8b94-80687774e0c9)

**Comment by swansonk14** [comment]
Hi Evert,

Thanks for bringing up this issue! I see the molecule sketcher on my local version, so I'm not entirely sure what's going on. The molecule sketcher is the [JSME](https://jsme-editor.github.io/) sketcher. I copied their code into this directory: https://github.com/swansonk14/admet_ai/tree/main/admet_ai/web/app/static/jsme. Can you check that you have this directory in your local installation?

If you do have the JSME files locally, can you check your web browser console to see if there are any errors related to loading JSME?

Best,
Kyle

**Comment by Evert-Homan** [comment]
Hi Kyle,

Looks like all the files are in place, but the Chrome console gives the following when starting the web app and then clicking on the 'Draw Molecule' button:

`GET http://mjolnir.scilifelab.se:5001/static/jsme/jsme/jsme.nocache.js net::ERR_ABORTED 404 (NOT FOUND)
predict.js:28 Uncaught ReferenceError: jsmeApplet is not defined
    at resizeJSME (predict.js:28:9)
    at HTMLLabelElement.<anonymous> (predict.js:59:9)
    at HTMLLabelElement.dispatch (jquery.min.js:2:41772)
    at y.handle (jquery.min.js:2:39791)

Best/Evert

**Comment by swansonk14** [comment]
Hi Evert,

Thanks for sharing the error message! I dug deeper into the JSME code and it looks like it included a .gitignore file that was stopping git from uploading some of the necessary JSME files. I removed the .gitignore and pushed the relevant files. Can you try pulling the latest code and let me know if it works now?

Thanks,
Kyle

**Comment by Evert-Homan** [comment]
Hi again,

I can confirm that the sketcher now works on my local install, after updating to the latest version. Many thanks, now I can roll this out internally.

BW/Evert

**Comment by Evert-Homan** [comment]
Off-topic: have you seen my issue with Synthemol? Appreciate if you could have alook.

Thanks/Evert
