### ISSUE TITLE
Reindexing only valid with uniquely valued Index objects

### ISSUE THREAD

**Issue by osangma** [swansonk14/admet_ai#8]
admet_predict in Cli Mode throw error:Reindexing only valid with uniquely valued Index objects, what's the reason and how fix it

**Comment by swansonk14** [comment]
Hi @osangma,

Thank you for bringing up this issue! Can you please provide a bit more context about the error? Can you share the exact command you tried to run, and if possible, the dataset you tried to run it on?

Thanks,
Kyle

**Comment by swansonk14** [comment]
Hi @osangma,

I'm going to close this issue, but please feel free to reopen it if you're still having issues.

Best,
Kyle
