### ISSUE TITLE
relax `requirements.txt`? 

### ISSUE THREAD

**Issue by corinwagen** [swansonk14/admet_ai#9]
Hey, thanks for putting out such a great package!

I'm struggling with installing this into an environment with a number of other packages - is it 100% necessary to pin every requirement to the exact version in `requirements.txt`? 

```
chemfunc==1.0.4
chemprop==1.6.1
flask==3.0.0
gunicorn==21.2.0
numpy==1.25.2
openpyxl==3.1.2
pandas==2.1.0
PyTDC==0.4.1
rdkit==2023.3.3
seaborn==0.13.0
tqdm==4.66.1
typed-argument-parser==1.9.0
```

In particular, the `numpy`/`pandas`/`rdkit` specifications seem pretty tight, particularly in light of standard semantic versioning.

**Comment by swansonk14** [comment]
Hi @corinwagen,

Thank you for your interest in ADMET-AI!

You don’t have to strictly follow the `requirements.txt` versions. I pinned those specific versions for anyone who wants to exactly reproduce the results from our paper, but I think most of the recent versions of those packages should work. If you run `pip install admet-ai` or `pip install -e .` for the local installation, that will use the package version requirements in `setup.py` which are much more flexible than those in `requirements.txt`.

Please let me know if that works or if you’re still having version issues.

Best,
Kyle

**Comment by corinwagen** [comment]
Ah, apologies, I didn't realize `setup.py` had different config settings here. `pandas` is still giving me issues but I can use version 1.2.0 to get around that - thanks for the quick response!

Package is working great so far - much appreciated!
